env:
  global:
    secure: "NgdajgHW+WYCW+z8pX90TRWsL0hhdlXuWOT0TrV1q4EcvXuhru73F1ZgGWh0YJio4QzQdKhnFRzJ/WuxuIx+RkFnbbN1T2zZaC+K40GgOf2z30f+Yuite0b/41/o4SRqUwJ+T3Y2Edc+yHQJz9L9ioib0r1rwFGzn4acrrPr0bJpdDThxmRjAZTrLJLI+W0mwSy8DVDbDMGtZtQpAXE+0Z6ypoGLXrgMYENVJka7DjQAE/AK5B0riGS9fIPcbhmw3pUoiRboMKWkCkmeEd5CC+3Ly96GtQ+b040HNhFhmNf939m7CivoV+rA91i1YNEca5nCJsFhJGsimjPHwykA3hyUMS50TYacjjGLClCexoGLke/QaWhN575cn0f/zkBxzvlPxs4LOUmGsftEc7eUMck0MSEvqm/LOKjq+Kn+QuicM1INlCNPZfXQF/KKeRae7VyUBB9rZLcTe4gXvpHzu3pYowL7rNRDYW0nVJbZGbBevUEvX9fMD7rm6Zr2qddyLWV1bLkoYhCka/YOccKtBvMJ9v2FJTk8H8qFC4ChyKkAFKNbETgYBjKem8pN2QG0fkOmCgAm6deIYbKiTjqjoKFYvqPZVIpEFMxx4B2jadpin+aezSf7KstJJYCMVmvaBlZJiQ94/7D/gWcGc5/xV+CKiKUJoKc2semEB09TIAA="

addons:
  apt:
    packages:
    - librsvg2-bin

script:
- ./build.sh

